import type { PropsWithChildren } from 'react'
import type { Metadata } from 'next'

import './globals.scss'

export const metadata: Metadata = {
  title: 'Catalog Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
